### ISSUE TITLE
Login : User log in with incorrect credentials

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#10]
**Story description**

User logs in with incorrect credentials email and password:

**Sub tasks**

- [x] Errors are shown in form with react hook forms in client validation, required field.
- [x] Error are shown in toast in database validation when credentials don’t match with any data in database

**Comment by ivan-escribano** [comment]
Chenaged pattern min 6 caracthers, before was alfanumeric if wasnt alfanumeric didnt go in.

![Image](https://user-images.githubusercontent.com/82597141/195092172-6ef8a522-3340-4737-bdd7-066f1068a996.png)



CHANGED TO : 
![Image](https://user-images.githubusercontent.com/82597141/195092662-adbd2351-1349-4ded-b947-96c41e90cb70.png)

**Comment by ivan-escribano** [comment]
React-query changed to firebase directly: @reduansj 




![Image](https://user-images.githubusercontent.com/82597141/195093036-ce160ae5-6865-41e7-86a4-e1b79dc0c60c.png)
