### ISSUE TITLE
Login Style

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#11]
User enters to the app/login page and visualize the login form.

**Comment by ivan-escribano** [comment]
Responsive styles

**Comment by reduansj** [comment]
![Image](https://user-images.githubusercontent.com/95076022/196200194-7dc31978-a722-4a8e-a2b2-70fa8d78860e.PNG)
![Image](https://user-images.githubusercontent.com/95076022/196200192-7fd07e83-39dc-4224-8b81-fe16ee9e7b82.PNG)
![Image](https://user-images.githubusercontent.com/95076022/196200193-1cef2010-3ae5-497c-afea-6a595d00a0ae.PNG)
