### ISSUE TITLE
Register Style

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#15]
**Story description**

User enters to the register page and visualize the register form.

**Comment by ivan-escribano** [comment]
@MatiasPatrignani 

cambiar parametros 

![Image](https://user-images.githubusercontent.com/82597141/195099916-8ce93cdb-7333-4eff-963b-84950cb3c020.png)

**Comment by ivan-escribano** [comment]
@MatiasPatrignani 

Redireccion erronea?

![Image](https://user-images.githubusercontent.com/82597141/195181406-75b2e383-621e-4444-830a-69ad11d19e50.png)

**Comment by ivan-escribano** [comment]
Responsive styles

**Comment by ivan-escribano** [comment]
tabulador first name then last name

**Comment by reduansj** [comment]
![Image](https://user-images.githubusercontent.com/95076022/196200454-18c32f77-4dca-4406-b53c-b002962bf483.PNG)
![Image](https://user-images.githubusercontent.com/95076022/196200453-7222bcc9-58b6-4e19-bfaa-17c161995e6c.PNG)
