### ISSUE TITLE
Home / dashboard: Slides section with recommended songs

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#20]
**Story description**

Home/dashboard : This section recommends 3 songs form our database. (Random at first) fetch 3 songs random, need to fetch 3 songs from database

**Comment by averoli** [comment]
![Image](https://user-images.githubusercontent.com/64157643/195049535-32f9723c-c5a2-418b-bb56-d45d8a113202.png)
