### ISSUE TITLE
Home / dashboard Styles

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#24]
**Story description**

User access to the dashboard/home and can see:

**Sub tasks**
- [x] Dashboard style
- [x] 3 slides with 3 songs.
- [x] Your library section with libraries or button to create library if is empty.
- [x] Liked songs container or not liked songs message.

**Comment by MatiasPatrignani** [comment]
Responsive desing dashboard almost done.

**Comment by ivan-escribano** [comment]
Liked songs and your library @MatiasPatrignani @ivan-escribano
