### ISSUE TITLE
Search page: Search bar input section

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#26]
**Story description**

This section allows the user to click in the input than a modal appears.

**Sub tasks**

- [x] When type 4 characters in input, fetch songs that match the input with the songs name.
- [x] Show all matches in a list type of songs if no matches message.
- [x] On click to one song play the song and stored in “last song searched” array in database.
- [x] Like/dislike/add playlist functionality
- [x] #65

**Comment by reduansj** [comment]
Only need the function for reproduction of the song all other feats are done!
