### ISSUE TITLE
Profile: User updates image and email

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#45]
**Story description**

User’s updates and email and image:

**Sub tasks**

- [x] Needs validation in the client side with correct format email and image
- [x] Update in the database.

**Comment by ivan-escribano** [comment]
BASICS
	PASSWORD
		VERIFY ACCOUNT BEFORE CHANGE PASSWORD OK
		INPUT BLOCKED OK
		ON CLICK MODAL DISPLAY OK
		UPDATE PASSWORD OK
	EMAIL
		ADD CURRENT EMAIL IN INPUT OK
		VERIFY ACCOUNT BEFORE CHANGE EMAIL OK
		CHECK EMAIL EXIST BEFORE UPDATING OK
		UPDATE EMAIL OK
	PHOTOURL
		ADD CURRENT PROFILE PICTURE TO LABEL OK
		CHECK IF IMAGE IS THE SAME IF ITS THE SAME DONT SEND TO THE BACK OK
		IF IMAGE IS NEW DELETE THE OLD IN CLOUDINARY PENDING OK
		CHECK IF IMAGE IS NULL OR UNDEFINED AND NOT SEND TO BACK OK

	REACT HOOK FORMS
		CHECK VALIDATION FOR ALL PENDING
	STYLE
		STYLE PROFILE PENDING
