### ISSUE TITLE
Profile: User updates password

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#46]
**Story description**

Users clicks on change password:

**Sub tasks**

- [x] Old password is the actual password 
- [x] New password and confirm password are the same.
- [x] On save password is changed.

**Comment by ivan-escribano** [comment]
BASICS
	PASSWORD
		VERIFY ACCOUNT BEFORE CHANGE PASSWORD OK
		INPUT BLOCKED OK
		ON CLICK MODAL DISPLAY OK
		UPDATE PASSWORD OK
	EMAIL
		ADD CURRENT EMAIL IN INPUT OK
		VERIFY ACCOUNT BEFORE CHANGE EMAIL OK
		CHECK EMAIL EXIST BEFORE UPDATING OK
		UPDATE EMAIL OK
	PHOTOURL
		ADD CURRENT PROFILE PICTURE TO LABEL OK
		CHECK IF IMAGE IS THE SAME IF ITS THE SAME DONT SEND TO THE BACK OK
		IF IMAGE IS NEW DELETE THE OLD IN CLOUDINARY PENDING OK
		CHECK IF IMAGE IS NULL OR UNDEFINED AND NOT SEND TO BACK OK

	REACT HOOK FORMS
		CHECK VALIDATION FOR ALL PENDING
	STYLE
		STYLE PROFILE PENDING
