### ISSUE TITLE
General menu style

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#57]
**Story description**

User enters the app or any page of the app and it shows a general menu with these options: 

**Sub tasks**

- [x] Logo
- [x] Home
- [x] Search
- [x] Your library
- [x] Create playlist
- [x] Liked songs

**Comment by ivan-escribano** [comment]
Falta responsive and logo

**Comment by MatiasPatrignani** [comment]
![Image](https://user-images.githubusercontent.com/100035710/196443049-164957ee-408f-4214-bdea-3497a7eeaa8d.png)
