### ISSUE TITLE
Create model

### ISSUE THREAD

**Issue by LMprojects7E6** [LMprojects7E6/astro-sound#60]
Create models with mongoose

**Comment by ivan-escribano** [comment]
- Created models and tested with postman(Song , User , Playlist)



![Image](https://user-images.githubusercontent.com/82597141/194733875-7e5403ff-a48d-4262-a88b-8c1a2774828f.png)



![Image](https://user-images.githubusercontent.com/82597141/194733897-e23ef4d8-38e7-4e8b-8dfa-620baa26e851.png)




![Image](https://user-images.githubusercontent.com/82597141/194733972-e560cbfc-cbcd-4ec2-9e66-9f2a555f4843.png)
